name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta sea tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
